#if !canImport(ObjectiveC)
import XCTest

extension ListEntryCollectionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListEntryCollectionsTests = [
        ("testBidirectionalCollection", testBidirectionalCollection),
        ("testCollection", testCollection),
        ("testCount", testCount),
        ("testEmptyCollection", testEmptyCollection),
        ("testEmptySequence", testEmptySequence),
        ("testSequence", testSequence),
        ("testSlice", testSlice),
    ]
}

extension ListEntryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListEntryTests = [
        ("testAppend", testAppend),
        ("testEmpty", testEmpty),
        ("testFirst", testFirst),
        ("testInitialization", testInitialization),
        ("testInsert", testInsert),
        ("testLast", testLast),
        ("testList", testList),
        ("testPopFirst", testPopFirst),
        ("testPopLast", testPopLast),
        ("testRemove", testRemove),
        ("testRemoveFirst", testRemoveFirst),
        ("testRemoveLast", testRemoveLast),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ListEntryCollectionsTests.__allTests__ListEntryCollectionsTests),
        testCase(ListEntryTests.__allTests__ListEntryTests),
    ]
}
#endif
